/**
 * Even Fibonacci numbers
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be: 
 * 
 * 	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... 
 * 
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

int main()
{
	int prev_two = 1;
	int prev_one = 2;
	int curr = 0;
	int sum = 2;

	while (curr < 4000000) {
		if (curr % 2 == 0)
			sum += curr;

		curr = prev_two + prev_one;
		prev_two = prev_one;
		prev_one = curr;
	}

	printf("%d\n", sum);
	return 0;
}